inputSet:
  name: Build_maven_web_application_1691262104858-push-trigger-input-set
  identifier: Build_maven_web_application_1691262104858pushtriggerinputset
  orgIdentifier: default
  projectIdentifier: default_project
  pipeline:
    identifier: Build_maven_web_application_1691262104858
    properties:
      ci:
        codebase:
          build:
            type: branch
            spec:
              branch: <+trigger.branch>
